
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(fr"{os.getcwd()}\Component\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def inputGUI():
    window = Tk()

    window.geometry("1000x600")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 600,
        width = 1000,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    print(relative_to_assets("image_1.png"))
    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        500.0,
        300.0,
        image=PhotoImage(
            file=relative_to_assets("image_1.png"))
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_2 = canvas.create_image(
        523.0,
        325.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_3 = canvas.create_image(
        500.0,
        82.0,
        image=image_image_3
    )

    canvas.create_text(
        364.0,
        150.0,
        anchor="nw",
        text="Input From Keyboard",
        fill="#FFFFFF",
        font=("Poppins Bold", 25 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        312.5,
        262.0,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=185.0,
        y=242.0,
        width=255.0,
        height=38.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_2 = canvas.create_image(
        687.5,
        262.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=560.0,
        y=242.0,
        width=255.0,
        height=38.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_3 = canvas.create_image(
        687.5,
        350.0,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=560.0,
        y=330.0,
        width=255.0,
        height=38.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        615.0,
        439.0,
        image=entry_image_4
    )
    entry_4 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=560.0,
        y=419.0,
        width=110.0,
        height=38.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_solve.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=450.0,
        y=496.0,
        width=100.0,
        height=40.0
    )

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_5 = canvas.create_image(
        760.0,
        439.0,
        image=entry_image_5
    )
    entry_5 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_5.place(
        x=705.0,
        y=419.0,
        width=110.0,
        height=38.0
    )

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_6 = canvas.create_image(
        312.5,
        350.0,
        image=entry_image_6
    )
    entry_6 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_6.place(
        x=185.0,
        y=330.0,
        width=255.0,
        height=38.0
    )

    entry_image_7 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_7 = canvas.create_image(
        312.5,
        439.0,
        image=entry_image_7
    )
    entry_7 = Text(
        bd=0,
        bg="#F4F4F4",
        fg="#000716",
        highlightthickness=0
    )
    entry_7.place(
        x=185.0,
        y=419.0,
        width=255.0,
        height=38.0
    )

    canvas.create_text(
        175.0,
        219.0,
        anchor="nw",
        text="Buffer Size",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        550.0,
        219.0,
        anchor="nw",
        text="Sequence Count",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        550.0,
        307.0,
        anchor="nw",
        text="Maximum Sequence Length",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        550.0,
        396.0,
        anchor="nw",
        text="Matrix Width",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        695.0,
        396.0,
        anchor="nw",
        text="Matrix Height",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        175.0,
        307.0,
        anchor="nw",
        text="Unique Token Count ",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        175.0,
        396.0,
        anchor="nw",
        text="Token",
        fill="#FFFFFF",
        font=("Poppins Bold", 15 * -1)
    )

    canvas.create_text(
        175.0,
        459.0,
        anchor="nw",
        text="Note: Separate each token with space (E5 1C 77 ...)",
        fill="#FFFFFF",
        font=("Poppins Regular", 10 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
